package dev.phibus.s3.clickhouse;

import dev.phibus.s3.settings.BootstrapSecretCodec;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Duration;
import java.time.Instant;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;
import java.util.UUID;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@ConditionalOnProperty(name = "s3perf.application-mode", havingValue = "COORDINATOR", matchIfMissing = true)
public class ClickHouseProfileService {
    private final JdbcTemplate jdbc;
    private final BootstrapSecretCodec codec;
    public ClickHouseProfileService(JdbcTemplate jdbc, BootstrapSecretCodec codec) { this.jdbc=jdbc; this.codec=codec; }
    public List<Profile> list(){return jdbc.query("SELECT id,name,endpoints,database_name,username,connection_timeout_ms,query_timeout_seconds,is_default,created_at,updated_at FROM clickhouse_profile ORDER BY is_default DESC,name",this::map);}
    public Profile get(UUID id){var p=jdbc.query("SELECT id,name,endpoints,database_name,username,connection_timeout_ms,query_timeout_seconds,is_default,created_at,updated_at FROM clickhouse_profile WHERE id=?",this::map,id);if(p.isEmpty())throw new IllegalArgumentException("ClickHouse profile not found: "+id);return p.getFirst();}
    public ClickHouseConnectionSpec connectionSpec(UUID id,String requestedEndpoint){Profile p=get(id);String e=requestedEndpoint==null||requestedEndpoint.isBlank()?p.endpoints().getFirst():requestedEndpoint.trim();if(!p.endpoints().contains(e))throw new IllegalArgumentException("Endpoint is not part of ClickHouse profile: "+e);return new ClickHouseConnectionSpec(e,p.database(),p.username(),decryptPassword(id),p.connectionTimeoutMs(),p.queryTimeoutSeconds());}
    public Connection open(UUID id,String endpoint)throws SQLException{ClickHouseConnectionSpec s=connectionSpec(id,endpoint);Properties p=new Properties();p.setProperty("user",s.username());p.setProperty("password",s.password()==null?"":s.password());p.setProperty("connection_timeout",Integer.toString(s.connectionTimeoutMs()));p.setProperty("socket_timeout",Integer.toString(Math.multiplyExact(s.queryTimeoutSeconds(),1000)));return DriverManager.getConnection(jdbcUrl(s.endpoint(),s.database()),p);}
    @Transactional public Profile create(ProfileRequest r){validate(r);UUID id=UUID.randomUUID();if(r.defaultProfile())clearDefault();jdbc.update("INSERT INTO clickhouse_profile(id,name,endpoints,database_name,username,encrypted_password,connection_timeout_ms,query_timeout_seconds,is_default) VALUES (?,?,?,?,?,?,?,?,?)",id,r.name().trim(),normalizeEndpoints(r.endpoints()),defaultValue(r.database(),"default"),defaultValue(r.username(),"default"),encryptPassword(r.password()),normalizeConnectionTimeout(r.connectionTimeoutMs()),normalizeQueryTimeout(r.queryTimeoutSeconds()),r.defaultProfile());return get(id);}
    @Transactional public Profile update(UUID id,ProfileRequest r){get(id);validate(r);String old=encryptedPassword(id);String pw=r.password()==null||r.password().isBlank()?old:codec.encrypt(r.password());if(r.defaultProfile())clearDefault();jdbc.update("UPDATE clickhouse_profile SET name=?,endpoints=?,database_name=?,username=?,encrypted_password=?,connection_timeout_ms=?,query_timeout_seconds=?,is_default=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",r.name().trim(),normalizeEndpoints(r.endpoints()),defaultValue(r.database(),"default"),defaultValue(r.username(),"default"),pw,normalizeConnectionTimeout(r.connectionTimeoutMs()),normalizeQueryTimeout(r.queryTimeoutSeconds()),r.defaultProfile(),id);return get(id);}
    @Transactional public Profile makeDefault(UUID id){get(id);clearDefault();jdbc.update("UPDATE clickhouse_profile SET is_default=TRUE,updated_at=CURRENT_TIMESTAMP WHERE id=?",id);return get(id);}
    public void delete(UUID id){Profile p=get(id);if(p.defaultProfile())throw new IllegalArgumentException("Default ClickHouse profile cannot be deleted");jdbc.update("DELETE FROM clickhouse_profile WHERE id=?",id);}
    public DiscoveryResult discover(UUID id){Profile p=get(id);List<NodeDiscovery> n=new ArrayList<>();for(String e:p.endpoints())n.add(discoverNode(id,e,p));return new DiscoveryResult(p.id(),p.name(),n);}
    public NodeDiscovery test(ProfileRequest r){validate(r);Profile p=new Profile(UUID.randomUUID(),r.name(),splitEndpoints(r.endpoints()),defaultValue(r.database(),"default"),defaultValue(r.username(),"default"),normalizeConnectionTimeout(r.connectionTimeoutMs()),normalizeQueryTimeout(r.queryTimeoutSeconds()),false,Instant.now(),Instant.now());return discoverNodeTransient(p.endpoints().getFirst(),p,r.password()==null?"":r.password());}
    private NodeDiscovery discoverNode(UUID id,String e,Profile p){Instant st=Instant.now();try(Connection c=open(id,e)){return discover(c,e,p,st);}catch(Exception x){return failed(e,st,x);}}
    private NodeDiscovery discoverNodeTransient(String e,Profile p,String pw){Instant st=Instant.now();try(Connection c=openTransient(e,p,pw)){return discover(c,e,p,st);}catch(Exception x){return failed(e,st,x);}}
    private NodeDiscovery discover(Connection c,String e,Profile p,Instant st)throws SQLException{String v=scalar(c,"SELECT version()",p.queryTimeoutSeconds());List<String> clusters=strings(c,"SELECT DISTINCT cluster FROM system.clusters ORDER BY cluster",p.queryTimeoutSeconds());long tables=count(c,"SELECT count() FROM system.tables WHERE database=?",p.database(),p.queryTimeoutSeconds());long rt=count(c,"SELECT count() FROM system.tables WHERE database=? AND engine LIKE 'Replicated%'",p.database(),p.queryTimeoutSeconds());long reps=count(c,"SELECT count() FROM system.replicas WHERE database=?",p.database(),p.queryTimeoutSeconds());long ro=count(c,"SELECT count() FROM system.replicas WHERE database=? AND is_readonly=1",p.database(),p.queryTimeoutSeconds());return new NodeDiscovery(e,true,v,clusters,tables,rt,reps,ro,Duration.between(st,Instant.now()).toMillis(),null);}
    private NodeDiscovery failed(String e,Instant st,Exception x){return new NodeDiscovery(e,false,null,List.of(),0,0,0,0,Duration.between(st,Instant.now()).toMillis(),rootMessage(x));}
    private Connection openTransient(String e,Profile p,String pw)throws SQLException{Properties x=new Properties();x.setProperty("user",p.username());x.setProperty("password",pw);x.setProperty("connection_timeout",Integer.toString(p.connectionTimeoutMs()));x.setProperty("socket_timeout",Integer.toString(Math.multiplyExact(p.queryTimeoutSeconds(),1000)));return DriverManager.getConnection(jdbcUrl(e,p.database()),x);}
    static String jdbcUrl(String e,String db){String n=e==null?"":e.trim();if(!(n.startsWith("http://")||n.startsWith("https://")))throw new IllegalArgumentException("ClickHouse endpoint must start with http:// or https://");while(n.endsWith("/"))n=n.substring(0,n.length()-1);return "jdbc:clickhouse:"+n+"/"+defaultValue(db,"default");}
    static void validate(ProfileRequest r){if(r==null||r.name()==null||r.name().isBlank())throw new IllegalArgumentException("ClickHouse profile name is required");List<String> e=splitEndpoints(r.endpoints());if(e.isEmpty())throw new IllegalArgumentException("At least one ClickHouse endpoint is required");for(String x:e)jdbcUrl(x,r.database());normalizeConnectionTimeout(r.connectionTimeoutMs());normalizeQueryTimeout(r.queryTimeoutSeconds());}
    private static List<String> splitEndpoints(String v){if(v==null||v.isBlank())return List.of();return v.lines().flatMap(l->List.of(l.split(",")).stream()).map(String::trim).filter(s->!s.isBlank()).distinct().toList();}
    private static String normalizeEndpoints(String v){return String.join("\n",splitEndpoints(v));} private static int normalizeConnectionTimeout(Integer v){int t=v==null?5000:v;if(t<100||t>120000)throw new IllegalArgumentException("Connection timeout must be 100..120000 ms");return t;} private static int normalizeQueryTimeout(Integer v){int t=v==null?30:v;if(t<1||t>3600)throw new IllegalArgumentException("Query timeout must be 1..3600 seconds");return t;}
    private static String scalar(Connection c,String sql,int t)throws SQLException{try(Statement s=c.createStatement()){s.setQueryTimeout(t);try(ResultSet r=s.executeQuery(sql)){return r.next()?r.getString(1):null;}}} private static List<String> strings(Connection c,String sql,int t)throws SQLException{try(Statement s=c.createStatement()){s.setQueryTimeout(t);try(ResultSet r=s.executeQuery(sql)){List<String> o=new ArrayList<>();while(r.next())o.add(r.getString(1));return List.copyOf(o);}}} private static long count(Connection c,String sql,String db,int t)throws SQLException{try(PreparedStatement s=c.prepareStatement(sql)){s.setQueryTimeout(t);s.setString(1,db);try(ResultSet r=s.executeQuery()){return r.next()?r.getLong(1):0;}}}
    private Profile map(ResultSet r,int row)throws SQLException{return new Profile(r.getObject("id",UUID.class),r.getString("name"),splitEndpoints(r.getString("endpoints")),r.getString("database_name"),r.getString("username"),r.getInt("connection_timeout_ms"),r.getInt("query_timeout_seconds"),r.getBoolean("is_default"),instant(r,"created_at"),instant(r,"updated_at"));} private String encryptedPassword(UUID id){return jdbc.queryForObject("SELECT encrypted_password FROM clickhouse_profile WHERE id=?",String.class,id);} private String decryptPassword(UUID id){String e=encryptedPassword(id);return e==null||e.isBlank()?"":codec.decrypt(e);} private String encryptPassword(String p){return p==null||p.isBlank()?null:codec.encrypt(p);} private void clearDefault(){jdbc.update("UPDATE clickhouse_profile SET is_default=FALSE,updated_at=CURRENT_TIMESTAMP WHERE is_default=TRUE");} private static Instant instant(ResultSet r,String c)throws SQLException{OffsetDateTime v=r.getObject(c,OffsetDateTime.class);return v==null?null:v.toInstant();} private static String defaultValue(String v,String f){return v==null||v.isBlank()?f:v.trim();} private static String rootMessage(Throwable e){Throwable c=e;while(c.getCause()!=null)c=c.getCause();return c.getMessage()==null?c.getClass().getSimpleName():c.getMessage();}
    public record ProfileRequest(String name,String endpoints,String database,String username,String password,Integer connectionTimeoutMs,Integer queryTimeoutSeconds,boolean defaultProfile){} public record Profile(UUID id,String name,List<String>endpoints,String database,String username,int connectionTimeoutMs,int queryTimeoutSeconds,boolean defaultProfile,Instant createdAt,Instant updatedAt){} public record NodeDiscovery(String endpoint,boolean reachable,String version,List<String>clusters,long tables,long replicatedTables,long replicas,long readonlyReplicas,long latencyMs,String error){} public record DiscoveryResult(UUID profileId,String profileName,List<NodeDiscovery>nodes){}
}
